HOME_DIR = '/var/lib/proms/'
STATIC_DIR = 'static/'
PROMS_DB_URI = 'http://localhost:5820/proms/query'
#PROMS_INSTANCE_NAMESPACE_URI = 'http://butterfree-bu.nexus.csiro.au/proms/'
PROMS_INSTANCE_NAMESPACE_URI = 'http://localhost:9000/'