from class_incoming import IncomingClass
import cStringIO
import uuid
from rdflib import Graph
import api_functions
import settings
from modules import rulesets as reportingsystem_ruleset
from modules.ldapi import LDAPI


class IncomingReportingSystem(IncomingClass):
    def __init__(self, data, mimetype):
        IncomingClass.__init__(self, data, mimetype)

    def valid(self):
        """Validates an incoming ReportingSystem using direct tests (can it be parsed?) and appropriate RuleSets"""
        # try to parse the Reportingsystem data
        try:
            self.graph = Graph().parse(
                cStringIO.StringIO(self.data),
                format=[item[1] for item in LDAPI.MIMETYPES_PARSERS if item[0] == self.mimetype][0]
            )
        except Exception, e:
            self.error_messages = ['The serialised data cannot be parsed. Is it valid RDF?',
                                   'Parser says: ' + e.message]
            return False

        # RuleSet
        conformant_report = reportingsystem_ruleset.ReportingSytems(self.graph)

        if not conformant_report.passed:
            self.error_messages = conformant_report.fail_reasons
            return False

        # if the Report has been parsed, we have found the Report type and it's passed it's relevant RuleSet, it's valid
        return True

    def determine_uri(self):
        """Determines the URI for this ReportingSystem"""
        # if this ReportingSystem has a placeholder URI, find it and replace it with one generated by PROMS Server
        q = '''
            SELECT ?uri
            WHERE {
                ?uri a <http://promsns.org/def/proms#ReportingSystem> .
                FILTER regex(str(?uri), "placeholder")
            }
        '''
        uri = None
        for r in self.graph.query(q):
            uri = r['uri']

        if uri is not None:
            self._generate_new_uri(uri)
        else:
            # since it has an existing URI, not a placeholder one, use the existing one
            q = '''
                SELECT ?uri
                WHERE {
                    ?uri a <http://promsns.org/def/proms#ReportingSystem> .
                }
            '''
            for r in self.graph.query(q):
                self.uri = r['uri']

        return True

    def _generate_new_uri(self, old_uri):
        # ask PROMS Server for a new RS URI
        new_uri = settings.REPORTINGSYSTEM_BASE_URI + str(uuid.uuid4())
        self.uri = new_uri
        # add that new URI to the in-memory graph
        api_functions.replace_uri(self.graph, old_uri, new_uri)
